### ISSUE TITLE
1.7 Crash that provides no information

### ISSUE THREAD

**Issue by Syer10** [lumien231/Loading-Profiler#2]
https://pastee.org/gngus
This crash happend to me constantly until i removed this mod, it has the newest forge witch is what I think is causing this.

**Comment by TomeWyrm** [comment]
Tested with Forge 1.7.10-10.13.3.1388 - Works
Tested with Forge 1.7.10-10.13.3.1389-1710ls - This crash

This is the version that added the loading bars, which I would assume is the root cause of the bug.
